/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

//import dao.AuditorDAO;
//import dao.KriteriaDAO;
//import dao.PerbandinganDAO;
//import java.util.List;
//import javax.swing.table.DefaultTableModel;
//import models.Auditor;
//import models.Kriteria;
//import utils.AHPCalculator;

/**
 *
 * @author USER
 */
public class view_hasilrangking extends javax.swing.JPanel {

    /**
     * Creates new form view_dashboard
     */
    public view_hasilrangking() {
        initComponents();
//        loadRangking();
    }

//    private void loadRangking() {
//        KriteriaDAO kriteriaDAO = new KriteriaDAO();
//        AuditorDAO auditorDAO = new AuditorDAO();
//        PerbandinganDAO perbandinganDAO = new PerbandinganDAO();
//
//        List<Kriteria> kriteriaList = kriteriaDAO.getAll();
//        List<Auditor> auditorList = auditorDAO.getAll();
//
//        if (kriteriaList.isEmpty() || auditorList.isEmpty()) return;
//
//        int nKriteria = kriteriaList.size();
//        int nAlternatif = auditorList.size();
//
//        // Hitung bobot kriteria
//        double[][] matriksKriteria = perbandinganDAO.buildMatriksKriteria(kriteriaList);
//        double[] bobotKriteria = AHPCalculator.hitungBobotPrioritas(matriksKriteria);
//
//        // Hitung bobot alternatif per kriteria
//        double[][] bobotAlternatif = new double[nKriteria][nAlternatif];
//        for (int k = 0; k < nKriteria; k++) {
//            int idKriteria = kriteriaList.get(k).getIdKriteria();
//            double[][] matriksAlt = perbandinganDAO.buildMatriksAlternatif(idKriteria, auditorList);
//            bobotAlternatif[k] = AHPCalculator.hitungBobotPrioritas(matriksAlt);
//        }
//
//        // Hitung nilai akhir & rangking
//        double[] nilaiAkhir = AHPCalculator.hitungNilaiAkhir(bobotKriteria, bobotAlternatif);
//        int[] rangking = AHPCalculator.getRangking(nilaiAkhir);
//
//        // Tampilkan tabel
//        String[] header = {"Peringkat", "Kode", "Nama Auditor", "Nilai Akhir", "Persentase"};
//        Object[][] data = new Object[rangking.length][5];
//        for (int rank = 0; rank < rangking.length; rank++) {
//            int idx = rangking[rank];
//            data[rank][0] = rank + 1;
//            data[rank][1] = auditorList.get(idx).getKodeAuditor();
//            data[rank][2] = auditorList.get(idx).getNamaAuditor();
//            data[rank][3] = String.format("%.3f", nilaiAkhir[idx]);
//            data[rank][4] = String.format("%.1f%%", nilaiAkhir[idx] * 100);
//        }
//        jTable1.setModel(new DefaultTableModel(data, header));
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Hasil Perangkingan ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(475, 475, 475))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
