/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

//import dao.KriteriaDAO;
import dao.KriteriaDAO;
import dao.SubKriteriaDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.ItemKriteria;
import models.Kriteria;
import models.SubKriteria;
import views.vform.vform_datasubkriteria;

/**
 *
 * @author USER
 */
public class view_datasubkriteria extends javax.swing.JPanel {

    private int idKriteriaTerpilih = -1;

    /**
     * Creates new form view_dashboard
     */
    public view_datasubkriteria() {
        initComponents();
        LoadTableSubKriteria();
        KriteriaDAO dao = new KriteriaDAO();
        dao.loadKriteriaToComboBox(tkriteria);
        generateKodeSubKriteria();
        tkode.disable();
    }

    private void cariKriteria(String keyword) {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID Sub");
        model.addColumn("ID Kriteria");
        model.addColumn("Nama Kriteria");
        model.addColumn("Kode Sub");
        model.addColumn("Nama Sub");
        model.addColumn("Bobot");

        SubKriteriaDAO dao = new SubKriteriaDAO();

        for (SubKriteria sub : dao.search(keyword)) {

            model.addRow(new Object[]{
                sub.getIdSub(),
                sub.getIdKriteria(),
                sub.getNamaKriteria(),
                sub.getKodeSub(),
                sub.getNamaSub(),
                sub.getBobot()
            });
        }

        tblkriteria.setModel(model);
    }

    private void LoadTableSubKriteria() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID Sub");
        model.addColumn("ID Kriteria");
        model.addColumn("Nama Kriteria");
        model.addColumn("Kode Sub");
        model.addColumn("Nama Sub");
        model.addColumn("Bobot");

        SubKriteriaDAO dao = new SubKriteriaDAO();

        try {

            ResultSet rs = dao.getDataSubkriteria();

            while (rs != null && rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("id_sub"),
                    rs.getInt("id_kriteria"),
                    rs.getString("nama_kriteria"),
                    rs.getString("kode_sub"),
                    rs.getString("nama_sub"),
                    rs.getDouble("bobot")
                });

            }

        } catch (SQLException e) {
            System.err.println("Error Load Table : " + e.getMessage());
        }

        tblkriteria.setModel(model);
    }

    private void generateKodeSubKriteria() {

        SubKriteriaDAO dao = new SubKriteriaDAO();

        String kode = dao.generateKode();

        tkode.setText(kode);
    }

    private void resetForm() {

        tkode.setText("");
        tkriteria.setSelectedIndex(0);
        tsubkriteria.setText("");
        tbobot.setText("");
        tkode.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkriteria = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tkode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        tsubkriteria = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tbobot = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tkriteria = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Sub Kriteria");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Cari");

        tcari.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcariKeyPressed(evt);
            }
        });

        tblkriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblkriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkriteriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblkriteria);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Form Data Auditor");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Kode");

        tkode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setText("Kriteria");

        btnsimpan.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        tsubkriteria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setText("Sub ");

        tbobot.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Bobot");

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tkriteria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        tkriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Kriteria--" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jSeparator1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(487, 487, 487)
                                .addComponent(jLabel1))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(82, 82, 82)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tsubkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
                                            .addComponent(tkode)
                                            .addComponent(tkriteria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(92, 92, 92)
                                            .addComponent(tbobot, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(158, 158, 158)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jSeparator3)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnbatal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButton1))
                                                .addComponent(jSeparator4))
                                            .addGap(0, 0, Short.MAX_VALUE))))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tkriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tsubkriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnubah)
                    .addComponent(btnhapus)
                    .addComponent(btnbatal)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        javax.swing.JPanel parent = (javax.swing.JPanel) this.getParent();

        parent.removeAll();
        parent.add(new vform_datasubkriteria());
        parent.revalidate();
        parent.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed

        resetForm();
        generateKodeSubKriteria();
        btnsimpan.setVisible(true);
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        if (idKriteriaTerpilih <= 0) {
            JOptionPane.showMessageDialog(this, "Pilih data sub kriteria yang ingin dihapus dari tabel terlebih dahulu!");
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus sub kriteria ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == JOptionPane.YES_OPTION) {
            SubKriteriaDAO dao = new SubKriteriaDAO();
            boolean berhasil = dao.delete(idKriteriaTerpilih);

            if (berhasil) {
                JOptionPane.showMessageDialog(this, "Data Sub Kriteria berhasil dihapus!");
                idKriteriaTerpilih = -1;
                resetForm();
                LoadTableSubKriteria();
                generateKodeSubKriteria();
                btnsimpan.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data Sub Kriteria.");
            }
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        if (idKriteriaTerpilih == 0) {
            JOptionPane.showMessageDialog(this,
                    "Silakan pilih data yang akan diubah!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tkriteria.getSelectedItem()
                == null) {
            JOptionPane.showMessageDialog(this,
                    "Silakan pilih kriteria!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            double bobot = Double.parseDouble(tbobot.getText());

            Kriteria kriteria = (Kriteria) tkriteria.getSelectedItem();

            SubKriteria sub = new SubKriteria();

            sub.setIdSub(idKriteriaTerpilih);
            sub.setIdKriteria(kriteria.getIdKriteria());
            sub.setKodeSub(tkode.getText().trim());
            sub.setNamaSub(tsubkriteria.getText().trim());
            sub.setBobot(bobot);

            SubKriteriaDAO dao = new SubKriteriaDAO();

            if (dao.update(sub)) {

                JOptionPane.showMessageDialog(this,
                        "Data berhasil diubah.");
                resetForm();
                LoadTableSubKriteria();
                btnsimpan.setVisible(true);
                generateKodeSubKriteria();
                idKriteriaTerpilih = 0;
                tkode.disable();

            } else {

                JOptionPane.showMessageDialog(this,
                        "Data gagal diubah.");

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this,
                    "Bobot harus berupa angka!");

            tbobot.requestFocus();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }

    }//GEN-LAST:event_btnubahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // Validasi Kriteria
        if (tkriteria.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                    "Silakan pilih Kriteria!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            tkriteria.requestFocus();
            return;
        }

        // Validasi Kode Sub
        if (tkode.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Kode Sub Kriteria tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            tkode.requestFocus();
            return;
        }

        // Validasi Nama Sub
        if (tsubkriteria.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Nama Sub Kriteria tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            tsubkriteria.requestFocus();
            return;
        }

        // Validasi Bobot
        if (tbobot.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Bobot tidak boleh kosong!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            tbobot.requestFocus();
            return;
        }

        double bobot;

        try {
            bobot = Double.parseDouble(tbobot.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Bobot harus berupa angka!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            tbobot.requestFocus();
            return;
        }

        try {

            Kriteria kriteria = (Kriteria) tkriteria.getSelectedItem();

            SubKriteria sub = new SubKriteria();
            sub.setIdKriteria(kriteria.getIdKriteria());
            sub.setKodeSub(tkode.getText().trim());
            sub.setNamaSub(tsubkriteria.getText().trim());
            sub.setBobot(bobot);

            SubKriteriaDAO dao = new SubKriteriaDAO();

            if (dao.insert(sub)) {

                JOptionPane.showMessageDialog(this,
                        "Data Sub Kriteria berhasil disimpan.");
                resetForm();
                LoadTableSubKriteria();
                generateKodeSubKriteria();

            } else {

                JOptionPane.showMessageDialog(this,
                        "Data Sub Kriteria gagal disimpan.");

            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan : " + e.getMessage());

        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void tblkriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkriteriaMouseClicked
        int row = tblkriteria.getSelectedRow();

        if (row == -1) {
            return;
        }

        String kodeSub = tblkriteria.getValueAt(row, 3).toString();

        SubKriteriaDAO dao = new SubKriteriaDAO();
        SubKriteria sub = dao.getByKode(kodeSub);

        if (sub != null) {

            idKriteriaTerpilih = sub.getIdSub();

            tkode.setText(sub.getKodeSub());
            tsubkriteria.setText(sub.getNamaSub());
            tbobot.setText(String.valueOf(sub.getBobot()));

            // Memilih item JComboBox berdasarkan ID Kriteria
            for (int i = 0; i < tkriteria.getItemCount(); i++) {

                Object item = tkriteria.getItemAt(i);

                if (item instanceof Kriteria) {

                    Kriteria k = (Kriteria) item;

                    if (k.getIdKriteria() == sub.getIdKriteria()) {
                        tkriteria.setSelectedIndex(i);
                        break;
                    }
                }
            }
        }

        btnsimpan.setVisible(false);
    }//GEN-LAST:event_tblkriteriaMouseClicked

    private void tcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyPressed
        String keyword
                = tcari.getText().trim();

        if (keyword.isEmpty()) {

            LoadTableSubKriteria();
        } else {

            cariKriteria(keyword);
        }
    }//GEN-LAST:event_tcariKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tblkriteria;
    private javax.swing.JTextField tbobot;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField tkode;
    private javax.swing.JComboBox<String> tkriteria;
    private javax.swing.JTextField tsubkriteria;
    // End of variables declaration//GEN-END:variables
}
