/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views.vform;

//import dao.AuditorDAO;
import dao.SubKriteriaDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import views.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class vform_datasubkriteria extends javax.swing.JPanel {

    private int idAuditorTerpilih = -1;

    /**
     * Creates new form view_dashboard
     */
    public vform_datasubkriteria() {
        initComponents();
        LoadTableSubKriteria();
//        generateKodeAuditor();
//        tkode.disable();
    }

    private void LoadTableSubKriteria() {

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID Sub");
        model.addColumn("ID Kriteria");
        model.addColumn("Nama Kriteria");
        model.addColumn("Kode Sub");
        model.addColumn("Nama Sub");

        SubKriteriaDAO dao = new SubKriteriaDAO();

        try {

            ResultSet rs = dao.getDataSubkriteria();

            while (rs != null && rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("id_sub"),
                    rs.getInt("id_kriteria"),
                    rs.getString("nama_kriteria"),
                    rs.getString("kode_sub"),
                    rs.getString("nama_sub")
                });

            }

        } catch (SQLException e) {
            System.err.println("Error Load Table SubKriteria : " + e.getMessage());
        }

        tblsubkriteria.setModel(model);
    }
//
//    private void generateKodeAuditor() {
//
//        AuditorDAO dao = new AuditorDAO();
//
//        String kode = dao.generateKode();
//
//        tkode.setText(kode);
//    }
//    private void cariAuditor(String keyword) {
//
//        DefaultTableModel model
//                = new DefaultTableModel();
//
//        model.addColumn("ID");
//        model.addColumn("Kode");
//        model.addColumn("Nama");
//        model.addColumn("Jabatan");
//        model.addColumn("Status");
//
//        AuditorDAO dao = new AuditorDAO();
//
//        for (models.Auditor t : dao.search(keyword)) {
//
//            model.addRow(new Object[]{
//                t.getIdAuditor(),
//                t.getKodeAuditor(),
//                t.getNamaAuditor(),
//                t.getJabatan(),
//                t.getStatus()
//            });
//        }
//
//        tblauditor.setModel(model);
//    }
//    private void resetForm() {
//        tkode.setText("");
//        tnama.setText("");
//        talamat.setText("");
//        tstatus.setSelectedIndex(0);
//        tkode.requestFocus();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsubkriteria = new javax.swing.JTable();
        btntambahkriteria = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Data Sub Kriteria");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Cari");

        tcari.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcariKeyPressed(evt);
            }
        });

        tblsubkriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsubkriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsubkriteriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsubkriteria);

        btntambahkriteria.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btntambahkriteria.setText("Tambah Sub Kriteria");
        btntambahkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahkriteriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntambahkriteria))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambahkriteria)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcariKeyPressed
//        String keyword
//                = tcari.getText().trim();
//
//        if (keyword.isEmpty()) {
//
//            loadTableTeknisi();
//
//        } else {
//
//            cariAuditor(keyword);
//        }
    }//GEN-LAST:event_tcariKeyPressed

    private void tblsubkriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsubkriteriaMouseClicked
//        int row = tblauditor.getSelectedRow();
//
//        if (row == -1) {
//            return;
//        }
//
//
//        String kode = tblauditor.getValueAt(row, 1).toString();
//
//        dao.AuditorDAO dao = new dao.AuditorDAO();
//        models.Auditor a = dao.getByKode(kode); 
//
//        if (a != null) {
//
//            idAuditorTerpilih = a.getIdAuditor();
//
//            // Set data ke komponen form Anda
//            tkode.setText(a.getKodeAuditor());
//            tnama.setText(a.getNamaAuditor());
//            tjabatan.setText(a.getJabatan());
//            tstatus.setSelectedItem(a.getStatus());
//        }
//
//        btnsimpan.setVisible(false);
    }//GEN-LAST:event_tblsubkriteriaMouseClicked

    private void btntambahkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahkriteriaActionPerformed
        javax.swing.JPanel parent = (javax.swing.JPanel) this.getParent();

        parent.removeAll();
        parent.add(new view_datasubkriteria());
        parent.revalidate();
        parent.repaint();
    }//GEN-LAST:event_btntambahkriteriaActionPerformed

///

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntambahkriteria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblsubkriteria;
    private javax.swing.JTextField tcari;
    // End of variables declaration//GEN-END:variables
}
